
const JWT_SECRET_STRING = "2312321sdfsdcxadas2323131";
const FORGOT_PASSWORD_EXPIRY_DAYS = 1;
const LOGIN_EXPIRY_DAYS = 2;

module.exports = {
	JWT_SECRET_STRING,
	FORGOT_PASSWORD_EXPIRY_DAYS,
	LOGIN_EXPIRY_DAYS,
}
