module.exports = {
    transfer: "transfer",
    transferReceive: "transfer_receive",
    transferSend: "transfer_send",
    swap: "swap_ethereum",
    withdraw: "withdraw_ethereum",
    priviCreditCreated: "PRIVI_credit_creation",
    priviCreditModified: "PRIVI_credit_modified",
    priviCreditBorrowed: "PRIVI_credit_borrowing",
    priviCreditCollateral: "PRIVI_credit_collateral",
    priviCreditWithdrawn: "PRIVI_credit_withdraw",
    priviCreditInterest: "PRIVI_credit_interest",
    priviCreditRiskAssumed: "PRIVI_risk_taking",
    priviCreditDeposited: "PRIVI_credit_deposit",
    priviCreditInterest: "PRIVI_interest_charge",
    traditionalBorrow: "traditional_borrowing",
    traditionalRepay: "repay_traditional",
    traditionalDepositCollateral: "traditional_collateral_deposit",
    traditionalWithdrawCollateral: "traditional_collateral_withdraw",
    traditionalInterest: "lending_interest",
    traditionalLiquidation: "traditional_liquidated",

    staking: "PRIVI_Staking",
    unstaking: "PRIVI_Unstaking",
    stakingReward: "Staking_Reward", // might be depricated
    mintingStaking: "Minting_Staking",


    podCreation: "POD_creation",
    podDeletion: "POD_deletion",
    podInvestment: "POD_investment",
    podPayInterest: "POD_pay_interest",
    podGetInterest: "POD_get_interest",
    podSwapGive: "POD_swap_give",
    podSwapGet: "POD_swap_get",
    nftPodCreation: "NFT_Pod_Creation",
    nftPodBuyOffer: "NFT_Pod_Buy_Offer",
    nftPodSellOffer: "NFT_Pod_Sell_Offer",
    nftPodBuyOfferDelete: "NFT_Pod_Buy_Delete",
    nftPodSellOfferDelete: "NFT_Pod_Sell_Delete",
    nftPodBuying: "NFT_Pod_Buying",
    nftPodSelling: "NFT_Pod_Selling",
    podLiquidationCollateral: "POD_liquidation_collateral",
    podLiquidationFunds: "POD_liquidation_funds",
    podBurningToken: "POD_burning_token",


    liquidityPoolCreation: "liquidity_pool_creation",
    liquidityPoolProvide: "liquidity_pool_provide",
    liquidityPoolSwap: "liquidity_pool_swap",
    liquidityPoolProtect: "liquidity_pool_protect",
    liquidityPoolList: "liquidity_pool_list",
    swapTrade: "Swap_trade",
    swapTradeFee: "Swap_trade_fee",
}