module.exports = {
    transferReceive: "transfer_receive",
    transferSend: "transfer_send",
    swap: "swap_ethereum",
    withdraw: "withdraw_ethereum",
    priviCreditCreated: "PRIVI_credit_creation",
    priviCreditModified: "PRIVI_credit_modified",
    priviCreditBorrowed: "PRIVI_credit_borrowing",
    priviCreditWithdrawn: "PRIVI_credit_withdraw",
    priviCreditRiskAssumed: "PRIVI_risk_taking",
    priviCreditDeposited: "PRIVI_credit_deposit",
    priviCreditInterest: "PRIVI_interest_charge",
    traditionalBorrow: "traditional_borrowing",
    traditionalRepay: "repay_traditional",
    traditionalDepositCollateral: "traditional_collateral_deposit",
    traditionalWithdrawCollateral: "traditional_collateral_withdraw",
}