module.exports = {
    user: "User",
    wallet: "Wallet",
    history: "History",
    allTransactions: "AllTransaction",
    waitlist: "Waitlist",
    cloudDatabase: "CloudDatabase",
    priviCredits: "PriviCredits",
    podsFT: "PodsFT",
    podsNFT: "PodsNFT",
    liquidityPools: "LiquidityPools",
    insurancePools: "InsurancePools",
    notificaction: "Notification",
    privacy: "EnabledPrivacy",
    rates: "ratesOfChange",
    rateHistory: "rateHistory",
    constants: "manualConstants",
    traditionalLendingConstants: "TraditionalLendingConstants",
    podFTConstants: "FTPodConstants",
    podNFTConstants: "NFTPodConstants",
    reserveConstants: "StakingReserveContants",

}