module.exports = {
    user: "User",
    tokens: "Tokens",
    wallet: "Wallet",
    walletNFT: "WalletNFT",
    walletFT: "WalletFT",

    cryptoToken: "CRYPTO",
    nftToken: "NFTPOD",
    ftToken: "FTPOD",
    socialToken: "SOCIAL",
    communityToken: "COMMUNITY",
    badgeToken: "BADGE",

    cryptoHistory: "CryptoHistory",
    nftHistory: "NftHistory",
    ftHistory: "FtHistory",
    socialHistory: "SocialHistory",
    communityHistory: "CommunityHistory",

    unknown: "UNKNOWN",
    tokens: "Tokens",
    priviScan: "PriviScan",
    history: "History",
    allTransactions: "AllTransaction",
    ethTransactions: "EthTransactions",
    waitlist: "Waitlist",
    cloudDatabase: "CloudDatabase",

    priviCredits: "PriviCredits",
    priviCreditsLending: "PriviCreditsLending",
    priviCreditsBorrowing: "PriviCreditsBorrowing",
    priviCreditsTransactions: "PriviCreditsTransactions",
    priviCreditInterestHistory: "PriviCreditsInterestHistory",
    priviCreditDepositedHistory: "PriviCreditsDepositedHistory",
    priviCreditBorrowedHistory: "PriviCreditsBorrowedHistory",
    priviCreditAvailableHistory: "PriviCreditsAvailableHistory",

    community: 'Community',
    communityLP: 'CommunityLP',
    communityTransactions: 'CommunityTransactions',
    votation: 'Votation',
    votationState: 'VotationState',
    voter: 'Voter',
    voting: 'Voting',

    podsFT: "PodsFT",
    buyingOffers: "BuyingOffers",
    sellingOffers: "SellingOffers",
    podsNFT: "PodsNFT",
    podTransactions: "PodTransactions",
    priceOfTheDay: "PriceOfTheDay",
    priceHistory: "PriceHistory",
    supplyHistory: "SupplyHistory",
    podRoleInvitation: "PodRoleInvitation",
    podViewInvitation: "PodViewInvitation",
    insurancePools: "InsurancePools",
    insuranceClients: "InsuranceCleints",
    insuranceInvestors: "InsurnaceInvestors",
    notificaction: "Notification",
    privacy: "EnabledPrivacy",
    rates: "ratesOfChange",
    rateHistory: "rateHistory",

    constants: "manualConstants",
    traditionalLendingConstants: "TraditionalLendingConstants",
    podFTConstants: "FTPodConstants",
    podNFTConstants: "NFTPodConstants",
    reserveConstants: "StakingReserveContants",
    reserveConstants: "StakingReserveContants",

    liquidityPools: "LiquidityPools",
    liquidityHistory: "LiquidityHistory",
    rewardHistory: "RewardHistory",

    stakingRates: "StakingRates",
    stakingDeposit: "StakingDeposit",
    stakingToken: "StakingToken",
    retunHistory: "ReturnHistory",
    stakedHistory: "StakedHistory",

    badges: "Badges",
    issues: "Issues",
    proposals: "Proposals",
    campaigns: "Campaigns",

    forumCategory: "ForumCategory",
    forumPost: "ForumPost",
    forumComment: "ForumComment",

    blogPost: "BlogPost",

    wallPost: "WallPost",

    podWallPost: "PodWallPost",
    creditWallPost: "CreditWallPost",
    insuranceWallPost: "InsuranceWallPost",
    communityWallPost: "CommunityWallPost",

    insurance: "Insurance",

    chat: "Chat",
    message: "Message",
    discordChat: "DiscordChat",
    discordRoom: "DiscordRoom",
    discordMessage: "DiscordMessage",
    discordMessageReplies: "DiscordMessageReplies",

    socialPools: "SocialPools",

    levels: "Levels",
}
